plugins:
  reek:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
  markdownlint:
    enabled: true
