version: "3.9"

services:
  postgres:
    image: postgres:14.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env

  streams:
    build: .
    entrypoint: ./docker-entrypoint.sh bash -c bin/dev
    env_file: .env
    tty: true
    volumes:
      - .:/streams
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres:
