version: "3.9"

services:
  psql:
    image: postgres:14.3-alpine
    volumes:
      - psql:/var/lib/postgresql/data
    env_file: .env

  rails:
    build: .
    entrypoint: ./docker-entrypoint.sh bash -c bin/dev
    env_file: .env
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - psql

volumes:
  psql:
